name: Daily Stock Update

on:
  schedule:
    # This cron schedule will trigger the action every day at 7:00 AM UTC
    - cron: "30 20 * * *" # Runs daily at 2:00 AM IST
  workflow_dispatch:

jobs:
  update-stock-data:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set Up Google Sheets Authentication
      env:
        SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      run: |
        echo "$SERVICE_ACCOUNT_JSON" > service_account.json
          
    # Step 4: Run the stock data update script
    - name: Run stock data update script
      run: |
        python update_stock_data.py

    # Step 5: Commit and push any changes (log and CSV files)
    - name: Set up Git
      run: |
        git config --global user.name "Aravinthkumar Stock Bot"
        git config --global user.email "aravinthkumarj1@gmail.com"
    
    - name: Authenticate and Push Changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/aravinthkumarj1/daily_stock_update.git
        git add logs/* csv/*
        git commit -m "Daily update: $(date)"
        git push origin main

