name: Fetch NSE Stock Data

on:
  schedule:
    - cron: "30 20 * * *" # Runs daily at 2:00 AM IST
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread yfinance

      - name: Set Up Google Sheets Authentication
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON" > service_account.json

      - name: Debug Service Account JSON File Content
        run: |
          echo "First 10 lines of service_account.json:"
          head -n 10 service_account.json

      - name: Validate JSON (Optional, you can remove if not needed)
        run: |
          python -c "import json; json.load(open('service_account.json'))"

      - name: Run NSE Data Update Script
        run: |
          python update_nse_parallel.py
