name: World_BQ_Score_Automation

on:
  #schedule:
    # Trigger the action every day at 7:00 PM IST (13:30 PM UTC)
    #- cron: "30 13 * * *"
  workflow_dispatch:

jobs:
  Fetch-world-stock-bigquery-score:
    runs-on: [self-hosted, windows]

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # Step 4: Set up Google Sheets Authentication
    #- name: Set Up Google Sheets Authentication
     # env:
      #  SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      #run: |
       # echo "$SERVICE_ACCOUNT_JSON" > service_account.json

    # Step 5: Configure Git
    - name: Set up Git
      run: |
        git config --global user.name "Aravinthkumar World BQ"
        git config --global user.email "aravinthkumarj1@gmail.com"


    # Step 7: Run the BSE stock data update script
    - name: Run BSE stock data BigQuery update script
      #if: ${{ env.continue == 'true' }}
      run: |
        python scripts/World_BQ_Score_Master.py

    - name: Authenticate and Push Changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        REM Configure Git for authentication
        git remote set-url origin https://x-access-token:%GH_PAT%@github.com/aravinthkumarj1/world_stock.git
    
        REM Configure Git LFS for handling large files
        git config --global lfs.required true  REM Enable Git LFS
        git lfs track "*.csv" "*.xls" "*.xlsx" "*.log"  REM Adjust based on your file types
    
        REM Show status and add necessary files
        git status
        git add scripts/* WORLD/*
    
        REM Commit changes
        git commit -m "%date% World stock update"
    
        REM Push changes to the repository
        git push origin main --force
